version: '3.9'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typeorm
      MYSQL_USER: thangtm
      MYSQL_PASSWORD: thangtm
    volumes:
      - ./data/mysql:/var/lib/mysql
